export type Language = "en" | "ta";
export type Claim = {
  id: string;
  scheme_id: string;
  claim_text: string;
  claim_text_ta: string;
  claim_type: string;
  status: string;
  document_id: string;
  source_page: number | null;
  excerpt: string;
  reporting_period: string;
  geographical_scope: string;
  population_scope: string;
  metric_name: string | null;
  metric_value: number | null;
  unit: string | null;
  verified_at: string | null;
  version: number;
  document?: DocumentRecord;
};
export type DocumentRecord = {
  id: string;
  title: string;
  organization: string;
  publication_date: string | null;
  document_type: string;
  source_level: "A" | "B" | "C" | "D";
  source_category: string;
  original_url: string;
  status: string;
  verified_at: string | null;
  source_domain_id?: string;
};
export type Scheme = {
  id: string;
  name_en: string;
  name_ta: string;
  slug: string;
  short_description_en: string;
  short_description_ta: string;
  department: string;
  category: string;
  launch_date: string | null;
  status: string;
  target_population: string;
  official_url: string;
  start_year: number;
  end_year: number | null;
  verification_status: string;
  last_verified_at: string | null;
};
export type Answer = {
  id: string;
  question: string;
  language: Language;
  direct: string;
  facts: { text: string; claimId: string }[];
  claims: Claim[];
  label: string;
  explanation: string;
  meaning: string;
  verifiedAt: string | null;
  generatedAt: string;
  conflicts: Claim[][];
  mode: string;
};
